[pytest]
# 告诉pytest去哪里找测试用例
testpaths = testcases

# 匹配规则：只运行以test_开头的py文件，和以test_开头的函数
python_files = test_*.py
python_functions = test_*

# 默认携带的参数：
# -s : 允许在控制台打印print内容
# -v : 显示详细的执行过程
# --alluredir : 把allure报告的临时数据存到 reports/allure-results 目录
addopts = -s -v --alluredir=./reports/allure-results --clean-alluredir